armonario_proj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import home, contact


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('contact/', contact, name='contact'),
    path('user/', include(('user_profile.urls', 'user_profile'), namespace='user')),
    path('calendar/', include(('calendar_view.urls', 'calendar_view'), namespace='calendar')),
    path('group/', include(('group_profile.urls', 'group_profile'), namespace='group')),
    path('event/', include(('event_view.urls', 'event_view'), namespace='event')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

event_view/urls.py
from django.urls import path
from . import views

app_name = 'event'

urlpatterns = [
    path('create/', views.create_event, name='create'),

]

group_profile/urls.py
from django.urls import path
from . import views

app_name = 'group_profile'

urlpatterns = [
    path('create/', views.create_group, name='create'),
    path('join/', views.list_group, name='join'),
    path('leave/<int:group_id>/', views.leave_group, name='leave'),

]

user_profile/urls.py
from django.urls import path
from . import views

app_name = 'user_profile'

urlpatterns = [
    path('register/', views.register_view, name='register'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('profile/', views.profile_view, name='profile'),
    path('edit/<int:user_id>', views.edit_view, name='edit_view'),
]

user_profile/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from cloudinary.models import CloudinaryField
import os


class CustomUser(AbstractUser):
    """
    CustomUser extends/builds upon the base User
    model so that custom fields can be added
    """
    location = models.CharField(max_length=100, blank=True)
    phone_number = models.CharField(max_length=50, blank=True)
    date_joined = models.DateTimeField(auto_now_add=True)
    picture = CloudinaryField(
        'image',
        default='default_profile',
        blank=True
    )

    def __str__(self):
        return self.username

user_profile/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django import forms

User = get_user_model()
# This code is based largely on the custom form built in
# the YouTube video by Codemy.com: https://www.youtube.com/watch?v=HdrOcreAXKk&t=397s


class CustomUserForm(UserCreationForm):
    """
    UserCreationForm is bound to the AUTH_USER_MODEL string
    This stops the form Meta.model from using default auth.User
    instead of this one
    """
    email = forms.EmailField()
    first_name = forms.CharField(max_length=50, required=True)
    last_name = forms.CharField(max_length=50, required=True)

    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('username', 'first_name', 'last_name', 'location',
                  'phone_number', 'email', 'password1', 'password2')


class CustomUserFormEdit(forms.ModelForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'location', 'phone_number', 'email', 'picture')
        widgets = {
            'first_name': forms.TextInput(attrs={'maxlength': 50}),
            'last_name': forms.TextInput(attrs={'maxlength': 50}),
        }

user_profile/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login, logout
from django.contrib.auth.forms import AuthenticationForm
from .forms import CustomUserForm, CustomUserFormEdit
from user_profile.models import CustomUser
from group_profile.models import UserGroupLink
# Create your views here.


def register_view(request):
    if request.method == 'POST':
        form = CustomUserForm(request.POST)
        if form.is_valid():
            login(request, form.save())
            return redirect("home")
    else:
        form = CustomUserForm()
    return render(request, 'user_profile/register.html', {'form': form})


def login_view(request):
    if request.method == "POST":
        # pass the request so AuthenticationForm can access request-specific
        # data (important for some authentication backends)
        form = AuthenticationForm(request=request, data=request.POST)
        if form.is_valid():
            login(request, form.get_user())
            return redirect("home")
    else:
        form = AuthenticationForm()
    return render(request, 'user_profile/login.html', {"form": form})


@login_required
def profile_view(request):
    user = request.user
    groupLinks = UserGroupLink.objects.filter(customUser=user).select_related('groupProfile')
    linkedGroups = []
    for link in groupLinks:
        item = {
            'group': link.groupProfile,
            'GroupShareCode': link.groupProfile.GroupShareCode,
            'GroupColour': link.groupProfile.GroupColour
        }
        linkedGroups.append(item)

    return render(request, 'user_profile/profile.html', {'linkedGroups': linkedGroups})


@login_required
def edit_view(request, user_id):
    """
    Edit the user profile view. CustomUserFormEdit
    has no password or username field to edit.
    """
    user = get_object_or_404(CustomUser, pk=user_id)

    if request.method == 'POST':
        form = CustomUserFormEdit(request.POST, request.FILES, instance=user,)
        if form.is_valid():
            form.save()
            return redirect('user:profile')
    else:
        form = CustomUserFormEdit(instance=user, )
    return render(request, 'user_profile/edit.html', {'form': form, 'user': user})


def logout_view(request):
    logout(request)
    return redirect("home")

user_profile/templates/user_profile/edit.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    {% comment " This skeleton code is based on a YouTube Tutorial by DaveGray www.youtube.com/watch?v=DIFaOkxy6TE " %}{% endcomment %}
    <section>
        <h1 class="title">EDIT YOUR PROFILE</h1>
        <hr>
        {% comment %} the addition of the enctype from the tutorial linked in readme for profile images {% endcomment %}
        <form method="post"
              enctype="multipart/form-data"
              class="form-with-validation">
            {% csrf_token %}
            {% if user.picture %}
                <img src="{{ user.picture.url }}" alt="Profile" style="max-width:200px">
            {% else %}
                {% comment %} else was a suggested fix from AI if the site should not be able to fetch the image {% endcomment %}
                <img src="{% static 'images/default_profile.webp' %}"
                     alt="Profile"
                     style="max-width:200px">
            {% endif %}
            {{ form }}
            <div class="slide-wrapper">
                <button type="submit" class="slide-button">
                    <span>Update Profile</span>
                </button>
            </div>
        </form>
    </section>
{% endblock content %}

user_profile/templates/user_profile/login.html
{% extends "base.html" %}
{% block content %}
    {% comment " This skeleton code is taken from a YouTube Tutorial by DaveGray www.youtube.com/watch?v=DIFaOkxy6TE " %}{% endcomment %}
    <section>
        <h1 class="title">USER LOGIN</h1>
        <hr>
        <form action="/user/login/" method="post" class="form-with-validation">
            {% csrf_token %}
            {{ form }}
            <div class="slide-wrapper">
                <button type="submit" class="slide-button">
                    <span>Login</span>
                </button>
            </div>
        </form>
    </section>
{% endblock content %}

user_profile/templates/user_profile/profile.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    <section>
        {% if user.is_authenticated %}
            <h1 class="title">{{ user|upper }} PROFILE</h1>
            <hr>
            <div class="container">
                {% if user.picture %}
                    <img src="{{ user.picture.url }}" alt="Profile" style="max-width:200px">
                {% else %}
                    <img src="{% static 'images/default_profile.webp' %}" alt="Profile">
                {% endif %}
                <ul>
                    <li>
                        <strong>E-mail:</strong> {{ user.email }}
                    </li>
                    <li>
                        <strong>First Name:</strong> {{ user.first_name }}
                    </li>
                    <li>
                        <strong>Last Name:</strong> {{ user.last_name }}
                    </li>
                    <li>
                        <strong>Phone Number:</strong> {{ user.phone_number }}
                    </li>
                    <li>
                        <strong>Location:</strong> {{ user.location }}
                    </li>
                </ul>
            </div>
            <h2>Your Groups</h2>
            {% for item in linkedGroups %}
                <div class="accordion-container">
                    <input type="checkbox"
                           id="accordion-{{ forloop.counter }}"
                           class="accordion-button" />
                    <label for="accordion-{{ forloop.counter }}"
                           style="background-color: {{ item.GroupColour }}">{{ item.group }}</label>
                    <div class="accordion-content">
                        <h2>{{ item.group }}</h2>
                        <p>
                            <strong>Share Code:</strong> {{ item.GroupShareCode }}
                        </p>
                        <div class="button-container">
                            <div class="slide-wrapper">
                                <a href="{% url 'group:leave' item.group.id %}"
                                   class="slide-button leave-group-btn">
                                    <span>Leave Group 💣</span>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            {% empty %}
                <p>You're not in any groups yet</p>
            {% endfor %}
            <div class="slide-wrapper" style="margin-top: 2rem;">
                <a href="{% url "user:edit_view" user.id %}" class="slide-button">
                    <span>Edit Profile ✍</span>
                </a>
            </div>
        {% else %}
            <h2>
                User not logged in, please <a href="{% url "user:login" %}">Log In</a> or <a href="{% url "user:register" %}">Sign-Up</a>
            </h2>
        {% endif %}
    </section>
{% endblock content %}
{% block extra_js %}
    <script src="{% static 'user_profile/js/user_profile.js' %}"></script>
{% endblock extra_js %}

user_profile/templates/user_profile/register.html
{% extends "base.html" %}
{% block content %}
    {% comment " This skeleton code is taken from a YouTube Tutorial by DaveGray www.youtube.com/watch?v=DIFaOkxy6TE " %}{% endcomment %}
    <section>
        <h1 class="title">USER REGISTER</h1>
        <hr>
        <form action="/user/register/" method="post" class="form-with-validation">
            {% csrf_token %}
            {{ form }}
            <div class="slide-wrapper">
                <button type="submit" class="slide-button">
                    <span>Register</span>
                </button>
            </div>
        </form>
    </section>
{% endblock content %}